rename from --with-... to --enable-...
--with-algebra-optimization ==> --enable-algebra-optimization
--with-gmp                  ==> --enable-gmp

git-svn-id: https://fricas.svn.sourceforge.net/svnroot/fricas/trunk@972 b0c55286-4f34-0410-a049-a1e7e93b0762

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1321,6 +1321,10 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --enable-gmp            use gmp for sbcl bignums
+  --enable-algebra-optimization=S
+                          use S as Lisp optimize declaration for compiling the
+                          algebra
   --enable-aldor          build an interface to the Aldor compiler
 
 Optional Packages:
@@ -1329,10 +1333,6 @@ Optional Packages:
   --with-noweb-tarball    specify place of the noweb-2.10a.tgz tarball
   --with-lisp=L           use L as Lisp platform
   --with-lisp-flavor=F    obsolete and ignored
-  --with-gmp              use gmp for sbcl bignums
-  --with-algebra-optimization=S
-                          use S as Lisp optimize declaration for compiling the
-                          algebra
   --with-x                use the X Window System
 
 Some influential environment variables:
@@ -4040,10 +4040,9 @@ esac
 ## In case our underlying lisp is SBCL, we provide a wrapper to enable
 ## GMP bignums in SBCL.
 GMP_WRAP_SO_TARGET=""
-
-# Check whether --with-gmp was given.
-if test "${with_gmp+set}" = set; then
-  withval=$with_gmp; case $withval in
+# Check whether --enable-gmp was given.
+if test "${enable_gmp+set}" = set; then
+  enableval=$enable_gmp; case $enableval in
                yes)
                  if test $fricas_lisp_flavor = sbcl ; then
                     case $(uname -m) in
@@ -4051,20 +4050,20 @@ if test "${with_gmp+set}" = set; then
                        GMP_WRAP_SO_TARGET=gmp_wrap_so
                          ;;
                       *)
-                       { { echo "$as_me:$LINENO: error: --with-gmp is valid only when using sbcl on AMD/Intel processors" >&5
-echo "$as_me: error: --with-gmp is valid only when using sbcl on AMD/Intel processors" >&2;}
+                       { { echo "$as_me:$LINENO: error: --enable-gmp is valid only when using sbcl on AMD/Intel processors" >&5
+echo "$as_me: error: --enable-gmp is valid only when using sbcl on AMD/Intel processors" >&2;}
    { (exit 1); exit 1; }; }
                          ;;
                     esac
                  else
-                    { { echo "$as_me:$LINENO: error: --with-gmp is valid only when using sbcl on AMD/Intel processors" >&5
-echo "$as_me: error: --with-gmp is valid only when using sbcl on AMD/Intel processors" >&2;}
+                    { { echo "$as_me:$LINENO: error: --enable-gmp is valid only when using sbcl on AMD/Intel processors" >&5
+echo "$as_me: error: --enable-gmp is valid only when using sbcl on AMD/Intel processors" >&2;}
    { (exit 1); exit 1; }; }
 
                  fi ;;
                no) ;;
-               *) { { echo "$as_me:$LINENO: error: --with-gmp only allows yes or no as an argument" >&5
-echo "$as_me: error: --with-gmp only allows yes or no as an argument" >&2;}
+               *) { { echo "$as_me:$LINENO: error: --enable-gmp only allows yes or no as an argument" >&5
+echo "$as_me: error: --enable-gmp only allows yes or no as an argument" >&2;}
    { (exit 1); exit 1; }; } ;;
              esac
 fi
@@ -5015,10 +5014,9 @@ esac
 
 fricas_algebra_optimization=nil
 
-
-# Check whether --with-algebra-optimization was given.
-if test "${with_algebra_optimization+set}" = set; then
-  withval=$with_algebra_optimization; fricas_algebra_optimization=$withval
+# Check whether --enable-algebra-optimization was given.
+if test "${enable_algebra_optimization+set}" = set; then
+  enableval=$enable_algebra_optimization; fricas_algebra_optimization=$enableval
 fi
 
 
