Added --enable-aldor feature.
git-svn-id: https://fricas.svn.sourceforge.net/svnroot/fricas/branches/aldor-interface@338 b0c55286-4f34-0410-a049-a1e7e93b0762

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1320,6 +1320,7 @@ Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --enable-gcl   build GCL from FriCAS source
+  --enable-aldor          build an interface to the Aldor compiler
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -8691,7 +8692,9 @@ ac_config_files="$ac_config_files src/etc/Makefile:config/var-def.mk:src/etc/Mak
 ##
 ## If one of the Aldor related tests fail we should warn and
 ## not build the Aldor interface. Default is to build it.
-BUILD_ALDOR_INTERFACE=build-axiom-interface
+## The test only fails if --enable-aldor is given explicitly
+## and some prerequisite is not available.
+BUILD_ALDOR_INTERFACE=build-aldor-interface
 
 ## check whether Aldor is available
 for ac_prog in aldor
@@ -8803,6 +8806,25 @@ echo "$as_me: WARNING: Couldn't find libfoam.al." >&2;}
   BUILD_ALDOR_INTERFACE=
 fi
 
+# Check whether --enable-aldor was given.
+if test "${enable_aldor+set}" = set; then
+  enableval=$enable_aldor; case $enableval in
+    yes) if test -z "$BUILD_ALDOR_INTERFACE"; then
+           { { echo "$as_me:$LINENO: error: prerequisites for Aldor interface missing" >&5
+echo "$as_me: error: prerequisites for Aldor interface missing" >&2;}
+   { (exit 1); exit 1; }; }
+         fi;;
+    no)  BUILD_ALDOR_INTERFACE=;;
+    *)   { { echo "$as_me:$LINENO: error: only yes/no allowed as value for --enable-aldor" >&5
+echo "$as_me: error: only yes/no allowed as value for --enable-aldor" >&2;}
+   { (exit 1); exit 1; }; };;
+   esac
+else
+  BUILD_ALDOR_INTERFACE=
+fi
+
+
+###################################################################
 # The installation is currently not done by recursively calling
 # install in the src subdirectories, so we have to hardcode the
 # intallation of the aldor interface in src/Makefile.in and let a
@@ -8810,10 +8832,12 @@ fi
 # installed.
 
 
-if test -z $BUILD_ALDOR_INTERFACE; then
+if test -z "$BUILD_ALDOR_INTERFACE"; then
   { echo "$as_me:$LINENO: WARNING: Aldor interface will not be built." >&5
 echo "$as_me: WARNING: Aldor interface will not be built." >&2;}
 else
+  { echo "$as_me:$LINENO: Aldor interface will be built." >&5
+echo "$as_me: Aldor interface will be built." >&6;}
   axiom_src_subdirs="$axiom_src_subdirs aldor"
   axiom_src_all="$axiom_src_all all-aldor"
   ac_config_files="$ac_config_files src/aldor/Makefile:config/var-def.mk:src/aldor/Makefile.in:config/setup-dep.mk"
