compile user guide into book.pdf

diff --git a/src/doc/Makefile.in b/src/doc/Makefile.in
--- a/src/doc/Makefile.in
+++ b/src/doc/Makefile.in
@@ -4,10 +4,15 @@
 #--- Copyright (C) 2013, 2014, 2020  Ralf Hemmecke <ralf@hemmecke.org>
 #---
 #------------------------------------------------------------------
-# The main target of this Makefile are "all".
+# The main target of this Makefile are "all" and "book.pdf".
+
+# Whereas "all" is made during normal FriCAS build, "book.pdf" must be
+# invoked separately.
 
 # The "all" target builds the contents of HyperDoc and creates the
 # .help files from their sources in src/doc/htex/ug16.htex.
+# The "doc" target builds the FriCAS book (book.pdf) and the website
+# that can be put at fricas.github.io.
 
 # "make all" puts everything into $(fricas_target_datadir).
 # It is responsible to make the graphics and (evaluated)
@@ -38,12 +43,32 @@
 # - The .ht files are copied to the target directory.
 # - The .help files are copied to the target directory for ")help ...".
 #
+# "make book.pdf" does the following:
+# - Copy pictures from the ps/ directory for (documentation of HyperDoc).
+# - Convert the *.VIEW/image.xpm pictures to .ps images (target stamp-pics).
+#   That expects all the .VIEW/ directories to exist (make viewports).
+#   It needs the convert program from ImageMagick. See ugepsf.awk.
+# - Generate tmo/ug09.tex with the list of examples.
+# - Create tmp/*.input from htex/*.htex (target ${HTEX_FILES_INPUT}).
+#   The .input files contain the commands that should be executed.
+#   All the other text from the .htex file is also included in the .input
+#   file but commented with "-- " prefix.
+# - Run the tmp/*.input files through bin/interpsy to produce
+#   tmp/*.spool files (target ${HTEX_FILES_SPOOL}).
+# - Turn the tmp/*.spool files into tmp/*.tex files (target ${HTEX_FILES_TEX}).
+# - Create tmp/info.tex with version information.
+# - LaTeX book.tex, call makeindex, and re-latex to get references right.
+# - Convert book.dvi to book.ps.
+# - Convert book.ps to book.pdf.
 #
 # ------------------------------------------------------------------
 # General notes
 #
-# Not everything is generated. There are a few .bitmap and .ht
+# Not everything is generated. There are a few .bitmap, .ps, and .ht
 # files in the sources.
+# The ps/*.ps files are pictures of HyperDoc windows and are included
+# in book.pdf (search for "\special{" in the sources). They are not
+# used for HyperDoc.
 # The .ht and .menu files are exclusively for display in HyperDoc.
 # The actual HyperDoc datebase however is ht.db.
 # Some .ht files are generated from .htex sources.
@@ -70,6 +95,7 @@ htexsrcdir   = ${srcdir}/htex
 htsrcdir     = ${srcdir}/ht
 bitmapssrcdir= $(srcdir)/bitmaps
 inputsrcdir  = ${fricas_src_srcdir}/input
+pssrcdir     = ${srcdir}/ps
 
 httargetdir        = $(fricas_target_datadir)/hypertex/pages
 bitmapstargetdir   = $(fricas_target_datadir)/hypertex/bitmaps
@@ -151,7 +177,7 @@ UGEPSF        = ${AWK} -f ${srcdir}/ugepsf.awk
 # book.pdf.
 # CHAPTER is the result of running:
 # find htex -name 'ug*.htex'|sed 's,.*ug,,;s,\.htex$,,'|sort
-CHAPTERS = 01 02 03 04 05 06 07 08   10 11 12 13 14 15 16   21
+CHAPTERS = 00 01 02 03 04 05 06 07 08   10 11 12 13 14 15 16   21
 HTEX_UGCHAPTERS = ${patsubst %, ug%, ${CHAPTERS}}
 
 # The chapter number as it will be put into generated .ht files for
@@ -212,10 +238,10 @@ GEN_HTFILES = xmpexp coverex gloss
 # windows in X and will make working during compilation impossible.
 # The intro.htex and util.ht files are not relevant for image generation.
 VIEWPORTFILES = coverex \
-  ${shell grep -lRe 'graphpaste\|spadgraph' ${srcdir}/ht/* ${srcdir}/htex/* \
+  $(shell grep -lRe 'graphpaste{\|spadgraph{' ${srcdir}/ht/* ${srcdir}/htex/* \
           | sed 's,.*/,,;s,\..*,,' \
 	  | grep -v util \
-          | sort}
+          | sort)
 # This should give
 # VIEWPORTFILES = coverex explot2d explot3d graphics SEGBIND \
 #                 ug01 ug07 ug08 ug10 ug11
@@ -250,7 +276,7 @@ HTEX_PASTEFILES = \
 ###################################################################
 # Chapter 10 of the FriCAS book refers to short programs (.input
 # files) that are stored under ${inputsrcdir}. They are used for
-# HyperDoc.
+# HyperDoc and book.pdf.
 # The list can be generated by the following command.
 # grep -R '\\spadcommand{)read' *| sed 's/[^ ]* //;s/[ \].*//'|sort -u
 INPUT_EXTRA = arrows bouquet newton ribbon vectors
@@ -554,9 +580,130 @@ dist:
 	    copy-to-dist
 
 
+###################################################################
+# Below this point are targets for building book.pdf.
+###################################################################
+# The following targets create .input files from .htex files. The
+# .input files contain the same text as the .htex file except that
+# anything outside of the second argument of an \xtc command appears
+# prefixed with "-- ". For simplicity, we require the \xtc command to
+# be written like this:
+## \xtc{
+##   SOME TEXT
+## }{
+##   COMMANDS
+## }
+# where SOME TEXT must not contain "}{" at the beginning of the line
+# and COMMANDS must not include "}" at the beginning of the line.
+# COMMANDS is either one line of the form
+## \spadcommand{.... \free{...} \bound{}}
+# where \free and \bound are optional or can occur multiple times or
+# of the form
+## \begin{spadsrc}[...]
+## ...
+## \end{spadsrc}
+###################################################################
+# The chapters used in HyperDoc and book.pdf that must be made from
+# the .htex files.
+HTEX_FILES = $(HTEX_UGCHAPTERS) $(HTEX_EXAMPLES)
+
+HTEX_FILES_INPUT = $(patsubst %, tmp/%.input, ${HTEX_FILES})
+${HTEX_FILES_INPUT}: tmp/%.input: ${htexsrcdir}/%.htex
+	${MKDIR_P} tmp
+	${HTEX2INPUT} $< > $@
+
+HTEX_FILES_SPOOL = ${patsubst %, tmp/%.spool, ${HTEX_FILES}}
+${HTEX_FILES_SPOOL}: tmp/%.spool: tmp/%.input
+	${MKDIR_P} tmp
+	echo ")read $<" | FRICAS_INITFILE='' ${INTERPSYS} > $@
+
+HTEX_FILES_TEX = ${patsubst %, tmp/%.tex, ${HTEX_FILES}}
+${HTEX_FILES_TEX}: tmp/%.tex: tmp/%.spool
+	${MKDIR_P} tmp
+	cat $< | ${SPOOL2TEX} > $@
+
+tmp/ug09.tex: tmp/examples.list
+	${MKDIR_P} tmp
+	${UGEXAMPLES} $< > $@
+
+pics.mk:
+	grep '\(\\head{\|\\psXtc\|\xtc\|\\noOutputXtc\|\\nullXtc\|epsffile\|\\spadgraph\)' ${srcdir}/htex/ug*.htex \
+	| ${UGEPSF} > $@
 
 ###################################################################
-clean-local:
+# There are a number of pictures for sections in book.pdf that
+# demonstrate the use of HyperDoc.
+PS_FILES = \
+  exit help home up	\
+  ribbon2r ribbons2 ribbons2b \
+  2Dctrl 3Dctrl SEGBIND arrowr knot3 \
+  h-alldoms h-allrank h-atsearch h-brfront h-comsearch h-consearch	\
+  h-docsearch h-gensearch h-matargs h-matats h-matdesc h-matexamp	\
+  h-matexports h-matimp h-matinv h-matmap h-matops h-matpage		\
+  h-matrelops h-matrixops h-matsource h-matxref h-root
+
+PS_FILES_PS = ${patsubst %, %.ps, ${PS_FILES}}
+${PS_FILES_PS}: %.ps: ${pssrcdir}/%.ps
+	cp $< $@
+
+stamp-pics: pics.mk viewports ${PS_FILES_PS}
+	${MAKE} -f pics.mk pics
+	${STAMP} $@
+
+###################################################################
+# In order to figure out the exact git hash that is used to produce
+# this book, we rely on the fact that we are inside a git repository.
+# If that is not the case, The info.tex file simply takes
+# ${PACKAGE_VERSION} for a clearer reference of the version of the
+# book. Note that the used variables can be overridden by setting
+# them on the "make" commandline.
+
+# Here lives the official git repository of the package.
+# It should be possible to say "git clone ${PACKAGE_SOURCE}".
+# Do not use ".git" extension explicitly for PACKAGE_SOURCE.
+PACKAGE_SOURCE=https://github.com/fricas/fricas
+
+tmp/info.tex:
+	${MKDIR_P} tmp
+	echo "\\begin{description}" > $@
+	echo "\\item[Website:] \url{${PACKAGE_URL}}" >> $@
+	echo "\\item[Repository:] \url{${PACKAGE_SOURCE}}" >> $@
+	if test -r ${top_srcdir}/.git/HEAD; then \
+	  (cd $(top_srcdir) && echo "\\item[Git hash:] \texttt{$$(git log -1 --pretty=%H)}");\
+	else \
+	  echo "\\item[FriCAS version:] ${PACKAGE_VERSION}"; \
+	fi >> $@
+	echo "\\end{description}" >> $@
+	echo >> $@
+
+# Convince latex to abort on error.
+LATEX=latex -halt-on-error -file-line-error -interaction=nonstopmode
+
+book.dvi: stamp-pics tmp/ug09.tex tmp/info.tex ${HTEX_FILES_TEX}
+	TEXINPUTS=$$TEXINPUTS:${srcdir}:tmp:. ${LATEX} book.tex \
+	|| (echo "==> Detected problem while running LaTeX."; \
+	    echo "==> LaTeX must be installed."; \
+	    echo "==> The following LaTeX packages must be available."; \
+	    echo "==> amsmath, breqn, tensor, mleftright, epsf, verbatim,"; \
+	    echo "==> hyperref, color, listings, makeidx, xparse, tikz"; \
+	    exit 1)
+	if grep 'LaTeX Warning: .*Rerun' book.log; then mv $@ tmp; fi
+
+book.ps: book.dvi
+	makeindex book
+	${MAKE} $<
+	${MAKE} $<
+	dvips $<
+
+book.pdf: book.ps
+	ps2pdf $<
+
+clean-book:
+	-rm -f info.tex pics.mk *.sfort ${PS_FILES_PS}
+	-rm -f ${patsubst %,book.%, aux idx ind out ps dvi ilg log pdf toc}
+
+###################################################################
+clean-local: clean-book
 	-rm -f ${GEN_NONVIEWPORTFILES_PHT} ${GEN_VIEWPORTFILES_PHT}
 	-rm -f ${GEN_FILES_HT} *.input *.help *.text *.ps
 	-rm -rf tmp
