Create macos dmg with 'mk_app dist'
Pull in the "create_dmg" script from
    https://github.com/create-dmg/create-dmg.git
and use it in the "mk_app dist" command to create a disk image suitable
for distribution. The final disk image will have a 500x320 window with a
shortcut to /Applications and the FriCAS icon.

Signed-off-by: Jeremy C. Andrus <jchristian.andrus@gmail.com>

diff --git a/contrib/macos/mk_app b/contrib/macos/mk_app
--- a/contrib/macos/mk_app
+++ b/contrib/macos/mk_app
@@ -77,12 +77,34 @@ if [ "${action}" == "build" ]; then
 fi
 
 if [ "${action}" == "dist" ]; then
-  tar cvJf FriCAS-${FRICASVER}-${ARCH}-macos${MACOSXVER}.tar.xz FriCAS.app
+
+  [ -d FriCAS.app ] || fail "Build the app first with $0 build"
+  [ -f FriCAS.dmg ] && rm FriCAS.dmg
+
+  mkdir -p dmg
+  mv FriCAS.app dmg
+  chmod +x create_dmg 2>/dev/null
+  ./create_dmg \
+	  --no-internet-enable \
+	  --volname FriCAS \
+	  --background fricas_dmg_background.png \
+	  --volicon appIcon.icns \
+	  --window-pos 200 120 \
+	  --window-size 500 320 \
+	  --icon-size 80 \
+	  --icon FriCAS.app 130 155 \
+	  --hide-extension FriCAS.app \
+	  --app-drop-link 375 155 \
+	  FriCAS.dmg dmg \
+	  || fail "Error building DMG - manual cleanup is probably necessary"
+  mv dmg/FriCAS.app .
+  rmdir dmg
 fi
 
 if [ "${action}" == "clean" ]; then
   rm -vrf ${SBCLDIR}
   rm -vrf FriCAS.app
+  rm -vrf FriCAS.dmg
   rm -vrf build
   rm -vf *~
 fi
